// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lilejyjiorezgnjosxma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpbGVqeWppb3Jlemduam9zeG1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MTc4ODQsImV4cCI6MjA2NzI5Mzg4NH0.M9jDFRJ0NhhNL5aJyiUrC3NUyY2lwIHyJtM6P5RcVy8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});